### ISSUE TITLE
[Bug] Keywords are not processed

### ISSUE THREAD

**Issue by olivierobert** [thuhtettun-geniefintech/tht-web-scraper#3]
## Issue

Upon uploading a CSV (and even the provided template), the following error is displayed:

![image](https://user-images.githubusercontent.com/696529/201294300-6a85385c-f6c6-433b-ab72-44ea13e1f630.png)

Apparently. the file was uploaded, or a record was created in the database:

![image](https://user-images.githubusercontent.com/696529/201294435-3eb5e5e1-2519-411f-adb8-87f592a36564.png)

However, when clicking to view details, there are indeed no keywords processed:

![Screenshot 2565-11-11 at 15 05 56](https://user-images.githubusercontent.com/696529/201295381-910fd15d-b7d4-40e8-9d1f-6bf5dbf0a69e.png)

## Expected

- File upload should succeed for the provided template file 🙈 
- In case of upload errors, the errors should be displayed on the web page (not on the console log error page)

**Comment by thuhtettun-geniefintech** [comment]
Thanks for your review.

I have updated it with Queue background process.
Can you please review it?

**Comment by olivierobert** [comment]
I can confirm that the scraping now works as expected

![image](https://user-images.githubusercontent.com/696529/201573192-34519bcd-f0c2-4ba9-ab79-955e8c1a0f4b.png)
